version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/postgres.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgresql_password
    secrets:
      - postgresql_password

  nextcloud:
    image: nextcloud
    restart: always
    depends_on:
      - db
    ports:
      - 9001:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - nextcloud_database_user
      - nextcloud_database_password
      - nextcloud_database

  passwords:
    image: mprasil/bitwarden:raspberry
    restart: always
    secrets:
      - bw_admin_token
    ports:
      - 443:80
    environment:
      ROCKET_TLS: '{certs="/ssl/certs.pem",key="/ssl/key.pem"}'
      ADMIN_TOKEN: /run/secrets/bw_admin_token
      LOG_FILE: /data/bitwarden.log
      ROCKET_LOG: critical
      EXTENDED_LOGGING: 'false'
    volumes:
      - /ssl/keys:/ssl/
      - /mnt/disk/bwdata/:/data/

  torrents:
    image: linuxserver/transmission
    restart: always
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    environment:
      TRANSMISSION_WEB_HOME: /transmission-web-control/
      PUID: 1000
      PGID: 1000
      TZ: 'Europe/Lisbon'
    volumes:
      - transmission_data:/config
      - /mnt/disk/exports/data/downloads:/downloads

volumes:
  postgres_data:
  nextcloud:
  transmission_data:

secrets:
  postgresql_password:
    external: true
  nextcloud_admin_password:
    external: true
  nextcloud_admin_user:
    external: true
  nextcloud_database:
    external: true
  nextcloud_database_password:
    external: true
  nextcloud_database_user:
    external: true
  bw_admin_token:
    external: true

