version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/postgres.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgresql_password
    secrets:
      - postgresql_password

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana_password
    volumes:
      - grafana_data:/var/lib/grafana
    secrets:
      - grafana_password

  passwords:
    image: mprasil/bitwarden:raspberry
    restart: always
    secrets:
      - bw_admin_token
    ports:
      - 443:80
    environment:
      ROCKET_TLS: '{certs="/ssl/certs.pem",key="/ssl/key.pem"}'
      ADMIN_TOKEN: /run/secrets/bw_admin_token
      LOG_FILE: /data/bitwarden.log
      ROCKET_LOG: critical
      EXTENDED_LOGGING: 'false'
    volumes:
      - /ssl/keys:/ssl/
      - /mnt/disk/bwdata/:/data/

  torrents:
    image: linuxserver/transmission
    restart: always
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    environment:
      TRANSMISSION_WEB_HOME: /transmission-web-control/
      PUID: 1000
      PGID: 1000
      TZ: 'Europe/Lisbon'
    volumes:
      - transmission_data:/config
      - /mnt/disk/exports/data/downloads:/downloads

  rss:
    image: linuxserver/freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - rss_data:/config
    ports:
      - 9090:80
    restart: unless-stopped

volumes:
  postgres_data:
  grafana_data:
  transmission_data:
  rss_data:

secrets:
  postgresql_password:
    external: true
  grafana_password:
    external: true
  bw_admin_token:
    external: true

