# https://severalnines.com/database-blog/using-kubernetes-deploy-postgresql

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_PASSWORD: admin123
