apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: rss
  name: rss
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: rss
    spec:
      containers:
      - env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: Europe/Lisbon
        image: linuxserver/freshrss
        name: rss
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: rss-data
      restartPolicy: Always
      volumes:
      - name: rss-data
        persistentVolumeClaim:
          claimName: rss-data
status: {}
